version: '3'

services:
    http-server:
        build: .
        container_name: rmqtt-http-server
#        command: uvicorn api:app --host 0.0.0.0 --port 80 --reload
        command: tail -f /dev/null
        volumes:
            # FOR DEVELOPING
            # - .:/home
            - /etc/localtime:/etc/localtime

    rmqtt1:
        container_name: rmqtt-node1
        image: rmqtt/rmqtt:latest
        environment:
            - TZ=Europe/Kiev
        volumes:
            - /var/rmqtt_data/etc:/app/rmqtt/etc
            - /var/rmqtt_data/log/1:/var/log/rmqtt
        ports:
            - "1883:1883"
            # - "8883:8883"
            # - "11883:11883"
            # - "6060:6060"
        restart: always
        command: -f /app/rmqtt/etc/rmqtt.toml --id 1

    influxdb:
        container_name: influxdb
        image: influxdb:2.6.1-alpine
        volumes:
            - influxdb-lib:/var/lib/influxdb2
        env_file:
            - ./.env
        expose:
            - "8086"
        restart: always
        privileged: true

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        command: -p 9999
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        logging:
            driver: none

    redis:
        container_name: redis
        image: redis
        command: >
            --requirepass ${REDIS_PASS}
        expose:
            - "6379"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - '127.0.0.1:3000:3000'
        volumes:
            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
#            - ./grafana/dashboards:/var/lib/grafana/dashboards
            - ./grafana/home-metrics.json:/var/lib/grafana/dashboards/home-metrics.json
            - grafana-storage:/var/lib/grafana
        links:
            - postgres
            - influxdb
            - redis
        environment:
            GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
            GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,redis-datasource"


volumes:
    influxdb-lib:
        external: false
    grafana-storage:


