apiVersion: 1

datasources:
- name: PSG
  type: postgres
  url: postgres:9999
  access: proxy
  user: adminikunikus
  database: postgres
  basicAuth: false
  isDefault: true
  jsonData:
     sslmode: disable
  version: 1
  editable: true
  secureJsonData:
    password: WVNufdM4bgqkq5LChYgqr8h

- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  jsonData:
    version: Flux
    organization: home-metrics
    defaultBucket: main
    tlsSkipVerify: true
  secureJsonData:
    token: KVgt7GLkE7mydG3PW4AaEdR2YnecvpWjmnScgDHD7425oJsKEyfR7q

- name: Redis
  type: redis-datasource
  access: proxy
  isDefault: false
  version: 1
  url: redis:6379
  jsonData:
    client: standalone
    poolSize: 5
    timeout: 10
    pingInterval: 0
    pipelineWindow: 0
  editable: true
  secureJsonData:
    password: 38RNeV5qAYhm7yazuRKknqb